### ISSUE TITLE
README编译中的一个小问题

### ISSUE THREAD

**Issue by doomlay** [eigeen/more-auto-shoutouts#1]
根据mhw-toolkit的`build.rs`
```
#[cfg(feature = "log")]
fn link_loader_ffi() {
    println!("cargo:rustc-link-lib=static=LoaderFFI");
}
```
如果要启用log feature的话，在编译的第4步，要把`LoaderFFI.lib`同时放到mhw-toolkit的lib里面。

**Comment by eigeen** [comment]
后来给feature更名为logger了，我统一一下命名防止混乱

**Comment by eigeen** [comment]
实际上编译此项目时只要该项目链接了就行，库的链接是调试时使用的

这里feature已经更名为logger，实际上是不起作用的，之后会处理一下这一块

**Comment by doomlay** [comment]
![3a0434b20f2442a7a1bf85609443ad4bd013021c](https://github.com/eigeen/more-auto-shoutouts/assets/135002409/70f95ed7-f284-4a98-beb6-71a83b08eb0c)
