### ISSUE TITLE
多余的move？

### ISSUE THREAD

**Issue by Jianqoq** [eigeen/more-auto-shoutouts#12]
`parse_config`这个函数里面的move貌似是多余的？如果是的话我实现触发器关联功能的时候可能会删掉这个东西

**Comment by eigeen** [comment]
能标注一下是哪一行的内容吗

**Comment by Jianqoq** [comment]
handlers.rs, 185

**Comment by eigeen** [comment]
没用上，但是并没有任何影响的。这个倒是无所谓
