### ISSUE TITLE
获取伤害有更好的方案吗

### ISSUE THREAD

**Issue by Jianqoq** [eigeen/more-auto-shoutouts#14]

**Comment by eigeen** [comment]
钩子已经是最好的方案了。另外钩子函数里有个参数是是否会心，只是还没写上

**Comment by Jianqoq** [comment]
目前获取伤害的性能有点差了，完全可以直接使用一个static mut DAMAGE: i32 = 0; 钩子函数里面直接改然后在异步任务里面读就行了，游戏全程调用伤害函数貌似只有一个线程，所以完全不需要锁。以后如果要收集伤害也只要自己写一个自己的thread local就行了，如果全程真的只用一个线程甚至都不用thread local

**Comment by eigeen** [comment]
> 目前获取伤害的性能有点差了，完全可以直接使用一个static mut DAMAGE: i32 = 0; 钩子函数里面直接改然后在异步任务里面读就行了，游戏全程调用伤害函数貌似只有一个线程，所以完全不需要锁。以后如果要收集伤害也只要自己写一个自己的thread local就行了，如果全程真的只用一个线程甚至都不用thread local

钩子最大的特点就是被动接收消息，因此在我的设计中，通过channel传递钩子消息几乎是必要的

不过这里static HOOKS_SENDER 倒是确实不用Mutex，因为我已经保证了该静态Sender一定是先初始化再被钩子调用的。所以虽然有unsafe，但是也可以去掉Mutex

**Comment by eigeen** [comment]
> > 目前获取伤害的性能有点差了，完全可以直接使用一个static mut DAMAGE: i32 = 0; 钩子函数里面直接改然后在异步任务里面读就行了，游戏全程调用伤害函数貌似只有一个线程，所以完全不需要锁。以后如果要收集伤害也只要自己写一个自己的thread local就行了，如果全程真的只用一个线程甚至都不用thread local
> 
> 钩子最大的特点就是被动接收消息，因此在我的设计中，通过channel传递钩子消息几乎是必要的
> 
> 不过这里static HOOKS_SENDER 倒是确实不用Mutex，因为我已经保证了该静态Sender一定是先初始化再被钩子调用的。所以虽然有unsafe，但是也可以去掉Mutex

算了还是不应该unsafe，这点性能开销可以忽略，Mutex就Mutex。
主要是HOOKS_SENDER设计用于多个钩子共享，因此要保证并发使用安全
