### ISSUE TITLE
全面支持Async/Await

### ISSUE THREAD

**Issue by eigeen** [eigeen/more-auto-shoutouts#15]
全面支持async/await，基于async_trait实现对Trait的异步支持

**Comment by eigeen** [comment]
@Jianqoq 不知道合并时你的计数代码有没有问题，请帮忙检查一下

**Comment by Jianqoq** [comment]
计数代码没问题

**Comment by eigeen** [comment]
> 计数代码没问题

计数器我改为宏字符串`{{counter}}`了，和其他的一致

**Comment by Jianqoq** [comment]
rust的trait默认就可以用async了吧，用async-trait有动态派发

Should I still use the #[async_trait] macro?

There are a couple of reasons you might need to continue using async-trait:

You want to support Rust versions older than 1.75.
You want dynamic dispatch.
As stated above, we hope to enable dynamic dispatch in a future version of the trait-variant crate.

**Comment by eigeen** [comment]
> rust的trait默认就可以用async了吧，用async-trait有动态派发
> 
> Should I still use the #[async_trait] macro?
> 
> There are a couple of reasons you might need to continue using async-trait:
> 
> You want to support Rust versions older than 1.75. You want dynamic dispatch. As stated above, we hope to enable dynamic dispatch in a future version of the trait-variant crate.

但我正在大量使用dyn trait
