### ISSUE TITLE
编译步骤错误

### ISSUE THREAD

**Issue by Jianqoq** [eigeen/more-auto-shoutouts#2]
将静态库放在 more-auto-shoutouts/lib 目录内

这个错了，应该是mhw-toolkit\lib

**Comment by eigeen** [comment]
其实没影响因为刚好改了feature的名字

后来注释掉了，因为库的静态链接只在调试时使用。rust的链接机制要求必须在主项目内有.lib，库里面没有是没关系的。除非我用cxx绑定
